stocks = [
    "ADESE.IS",
    "AEFES.IS",
    "AFYON.IS",
    "AGHOL.IS",
    "AGYO.IS",
    "AKBNK.IS",
    "AKCNS.IS",
    "AKENR.IS",
    "AKFGY.IS",
    "AKGRT.IS",
    "AKSA.IS",
    "AKSEN.IS",
    "ALARK.IS",
    "ALBRK.IS",
    "ALGYO.IS",
    "ALKA.IS",
    "ALKIM.IS",
    "ALMAD.IS",
    "ALYAG.IS",
    "ANACM.IS",
    "ANELE.IS",
    "ARCLK.IS",
    "ARENA.IS",
    "ARMDA.IS",
    "ARZUM.IS",
    "ASELS.IS",
    "ASUZU.IS",
    "ATAGY.IS",
    "ATATP.IS",
    "ATLAS.IS",
    "AVHOL.IS",
    "AVISA.IS",
    "AVOD.IS",
    "AYDEM.IS",
    "AYEN.IS",
    "AYGAZ.IS",
    "BAGFS.IS",
    "BAKAB.IS",
    "BANVT.IS",
    "BASGZ.IS",
    "BASIS.IS",
    "BAYRK.IS",
    "BERA.IS",
    "BIMAS.IS",
    "BIOEN.IS",
    "BIZIM.IS",
    "BJKAS.IS",
    "BLCYT.IS",
    "BNTAS.IS",
    "BRISA.IS",
    "BRMEN.IS",
    "BRYAT.IS",
    "BSOKE.IS",
    "BTCIM.IS",
    "BUCIM.IS",
    "BURCE.IS",
    "BURVA.IS",
    "CANTE.IS",
    "CCOLA.IS",
    "CELHA.IS",
    "CEMAS.IS",
    "CEMTS.IS",
    "CIMSA.IS",
    "CLEBI.IS",
    "COSMO.IS",
    "CRDFA.IS",
    "CRFSA.IS",
    "CUSAN.IS",
    "DAGHL.IS",
    "DAGI.IS",
    "DARDL.IS",
    "DENCM.IS",
    "DENIZ.IS",
    "DERIM.IS",
    "DESPC.IS",
    "DEVA.IS",
    "DGATE.IS",
    "DGGYO.IS",
    "DGKLB.IS",
    "DGRTR.IS",
    "DOAS.IS",
    "DOBUR.IS",
    "DOCO.IS",
    "DOGUB.IS",
    "DOHOL.IS",
    "DOKTA.IS",
    "DURDO.IS",
    "DYOBY.IS",
    "ECILC.IS",
    "ECZYT.IS",
    "EDATA.IS",
    "EDIP.IS",
    "EGCEY.IS",
    "EGCYH.IS",
    "EGGUB.IS",
    "EGPRO.IS",
    "EGSER.IS",
    "EGSIZ.IS",
    "EKGYO.IS",
    "EKIZ.IS",
    "ELITE.IS",
    "EMKEL.IS",
    "ENJSA.IS",
    "ENKAI.IS",
    "ERBOS.IS",
    "EREGL.IS",
    "ERSU.IS",
    "ESCAR.IS",
    "ETILR.IS",
    "EUHOL.IS",
    "EUKYO.IS",
    "EUPWR.IS",
    "FENER.IS",
    "FONET.IS",
    "FORMT.IS",
    "FRIGO.IS",
    "FROTO.IS",
    "GARAN.IS",
    "GEDIK.IS",
    "GEDZA.IS",
    "GENTS.IS",
    "GEREL.IS",
    "GLBMD.IS",
    "GLRYH.IS",
    "GLYHO.IS",
    "GOLTS.IS",
    "GOODY.IS",
    "GOZDE.IS",
    "GRNYO.IS",
    "GSDDE.IS",
    "GSDHO.IS",
    "GSRAY.IS",
    "GUBRF.IS",
    "GUSGR.IS",
    "GWIND.IS",
    "HALKB.IS",
    "HATEK.IS",
    "HDFGS.IS",
    "HEKTS.IS",
    "HUBVC.IS",
    "ICBCT.IS",
    "IDEAS.IS",
    "IDGYO.IS",
    "IHEVA.IS",
    "IHLAS.IS",
    "IHLGM.IS",
]
